spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bupt_hotel?serverTimezone=GMT
    username: root
    password: mufvycquzgek2qEbba
    driver-class-name: com.mysql.cj.jdbc.Driver

roomSum:
  number: 5
mybatis:
  type-aliases-package: com.example.backend.pojo


rooms:
  101:
    initialTem: 32.0
    feeEveryDay: 100
  102:
    initialTem: 28.0
    feeEveryDay: 125
  103:
    initialTem: 30.0
    feeEveryDay: 150
  104:
    initialTem: 29.0
    feeEveryDay: 200
  105:
    initialTem: 35.0
    feeEveryDay: 100

