spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bupt_hotel?serverTimezone=GMT
    username: root
    password: mufvycquzgek2qEbba
    driver-class-name: com.mysql.cj.jdbc.Driver
rooms:
  1:
    initialTem: 32.0
    feeEveryDay: 100
  2:
    initialTem: 28.0
    feeEveryDay: 125
  3:
    initialTem: 30.0
    feeEveryDay: 150
  4:
    initialTem: 29.0
    feeEveryDay: 200
  5:
    initialTem: 35.0
    feeEveryDay: 100
server:
  address: 10.129.194.103

